### PR TITLE
DECISION-17755 upgrading infra

### PR DESCRIPTION
**Pull request by ofirasor**
Angular 5.2 -> 7.2.3
TypeScript 2.9.1 -> 3.2.4
RxJS 5.5.10 -> 6.4.0

### CODE REVIEW

**Comment by Dekel-Cohen** [comment]
@ofirasor  Is it reaaly working?

**Comment by ofirasor** [comment]
@Dekel-Cohen 
seems to work, but I cant really test it because this project karma is really messed up
it did not work before my changes as well, its karma version and its `karma.conf` seems to be incompatible with latest chrome versions

**Comment by ofirasor** [comment]
@Dekel-Cohen 
I'll release it as a different version from this branch
Then I guess we will know only after I'll upgrade our ng-client and use it in it

**Comment by Dekel-Cohen** [comment]
@ofirasor  byw, maybe its better to start with ```decision-client-ng2``` and only then move the to other projects...

**Comment by urielTwito** [comment]
@ofirasor You can (and should) replace the current node_module with you new module (from dist)
check if it works and then deploy it

**Pull request merged**
